---
scrape_configs:
- job_name: redpanda
  scrape_interval: 15s
  scheme: http
  dns_sd_configs:
  - names: [ "redpanda" ]
    type: A
    port: 9644

- job_name: apiserver
  scrape_interval: 15s
  scheme: http
# static config to be used when running services locally and prometheus in a container
#  static_configs:
#    - targets: [ "host.docker.internal:8080" ]
  dns_sd_configs:
  - names: [ "apiserver" ]
    type: A
    port: 8080
- job_name: repo-meta-analyzer
  scrape_interval: 15s
  scheme: http
  metrics_path: /q/metrics
# static config to be used when running services locally and prometheus in a container
#  static_configs:
#    - targets: [ "host.docker.internal:8091" ]
  dns_sd_configs:
  - names: [ "repo-meta-analyzer" ]
    type: A
    port: 8091
- job_name: vuln-analyzer
  scrape_interval: 15s
  scheme: http
  metrics_path: /q/metrics
# static config to be used when running services locally and prometheus in a container
#  static_configs:
#    - targets: [ "host.docker.internal:8092" ]
  dns_sd_configs:
  - names: [ "vuln-analyzer" ]
    type: A
    port: 8092
# static config to be used when running services locally and prometheus in a container
#  static_configs:
#    - targets: [ "host.docker.internal:8093" ]