{{- if and .Values.apiServer.enabled .Values.apiServer.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "hyades.apiServerFullname" . }}
  {{- with .Values.apiServer.ingress.annotations }}
  annotations: {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  rules:
  - host: {{ .Values.apiServer.ingress.hostname | quote }}
    http:
      paths:
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: {{ include "hyades.apiServerFullname" . }}
            port:
              name: web
{{- end }}