{{- if .Values.apiServer.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "hyades.apiServerFullname" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{- include "hyades.apiServerLabels" . | nindent 4 }}
spec:
  type: {{ .Values.apiServer.service.type | quote }}
  ports:
  - name: web
    port: 8080
    targetPort: web
  selector: {{- include "hyades.apiServerSelectorLabels" . | nindent 4 }}
{{- end }}