# This file is part of Dependency-Track.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# SPDX-License-Identifier: Apache-2.0
# Copyright (c) OWASP Foundation. All Rights Reserved.
name: Update Config Documentation

on:
  push:
    branches:
    - main
    paths:
    - ".github/workflows/update-config-docs.yml"
    - "scripts/config-docs.md.peb"
    - "*/src/main/resources/application.properties"
  workflow_dispatch: { }

permissions: { }

jobs:
  generate-docs:
    name: Generate Documentation
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: write
      pull-requests: write
    if: "${{ github.repository_owner == 'DependencyTrack' }}"
    steps:
    - name: Checkout Repository
      uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # tag=v6.0.0
    - name: Checkout API Server Repository
      uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # tag=v6.0.0
      with:
        repository: DependencyTrack/hyades-apiserver
        path: hyades-apiserver
    - name: Generate API Server Documentation
      uses: jbangdev/jbang-action@d0ab22dc0ea8b6bf9114e50e44ba89b0fb939238 # tag=v0.135.0
      with:
        trust: https://github.com/DependencyTrack/jbang-catalog
        script: gen-config-docs@DependencyTrack
        scriptargs: >-
          --template ./scripts/config-docs.md.peb
          --output ./docs/reference/configuration/api-server.md
          ./hyades-apiserver/apiserver/src/main/resources/application.properties
    - name: Generate Repository Metadata Analyzer Documentation
      uses: jbangdev/jbang-action@d0ab22dc0ea8b6bf9114e50e44ba89b0fb939238 # tag=v0.135.0
      with:
        trust: https://github.com/DependencyTrack/jbang-catalog
        script: gen-config-docs@DependencyTrack
        scriptargs: >-
          --template ./scripts/config-docs.md.peb
          --output ./docs/reference/configuration/repo-meta-analyzer.md
          ./repository-meta-analyzer/src/main/resources/application.properties
    # TODO: Add script invocations for the other services here!
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@98357b18bf14b5342f975ff684046ec3b2a07725 # tag=v8.0.0
      with:
        add-paths: "docs/reference/configuration/*.md"
        branch: update-config-docs
        body: "Updates configuration documentation."
        commit-message: Update config docs
        delete-branch: true
        labels: documentation
        signoff: true
        title: Update config docs
